if [ -z "$REAL_TERM" ]; then
    case "$TERM" in
        *kitty*)   export REAL_TERM="kitty" ;;
        *wezterm*) export REAL_TERM="wezterm" ;;
        *ghostty*) export REAL_TERM="ghostty" ;;
        *)         export REAL_TERM="generic" ;;
    esac
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# If a comment has *BY KAZU* in it then it means it was commented out to avoid conflicts between the generated config and my own config.

# *BY KAZU* export ZSH="$HOME/.oh-my-zsh"

# *BY KAZU* ZSH_THEME="agnosterzak"

# *BY KAZU* plugins=( 
 # *BY KAZU*    git
 # *BY KAZU*    zsh-autosuggestions
 # *BY KAZU*    zsh-syntax-highlighting
# *BY KAZU* )

# *BY KAZU* source $ZSH/oh-my-zsh.sh


# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos
#pokemon-colorscripts --no-title -s -r #without fastfetch
# *BY KAZU* pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# fastfetch. Will be disabled if above colorscript was chosen to install
#fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc

# Set-up icons for files/directories in terminal using lsd
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

export PATH="$HOME/.local/bin:$PATH"

##################################################################################################################
########################## THE CODE ABOVE IS GENERATED BY HYPERLAND SETUP ########################################
##########################        THE CODE BELOW IS WRITTEN BY ME         ########################################
##################################################################################################################

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"

source "${ZINIT_HOME}/zinit.zsh"

zinit ice depth=1; zinit light romkatv/powerlevel10k

zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

zinit snippet OMZP::git

autoload -U compinit && compinit

zinit cdreplay -q

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# zinit light tolkonepiu/catppuccin-powerlevel10k-themes
# apply_catppuccin pure mocha

bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase

setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

zstyle ':completion:*' matches-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors "{(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# *BY KAZY* alias ls='ls --color'
alias c='clear'

source <(fzf --zsh)
eval "$(zoxide init --cmd cd zsh)"

# Swift SDK
export PATH="/usr/local/swift/usr/bin:$PATH"
source "$HOME/.swift-static-sdk.zsh"

# Flutter SDK
export PATH="/usr/local/flutter/bin:$PATH"

# Flutter MacOS Related
export PATH="$PATH":"$HOME/.pub-cache/bin"

alias tailwindcss='/usr/local/bin/tailwindcss'
alias matrix='gomatrix --kana --fps=24'

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PATH=$PATH:/usr/local/go/bin
export PATH=$(go env GOPATH)/bin:$PATH

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# neofetch --ascii ~/.wallpaper/apple.txt | lolcat
# alias anime='neofetch --backend kitty --source "$HOME/.config/neofetch/image/makeine.webp" --size 400px --crop_mode fit'

anifetch() {
    case "$REAL_TERM" in
        kitty|xterm-kitty|wezterm|xterm-ghostty|ghostty)
            # NOTE: Custom C Version of neofetch which uses kitten static binary so it should work as long as your terminal supports kitty image rendering protocol.
            /usr/local/bin/anime
            # NOTE: The following command only works if kitty is installed.
            # INFO: Will work if you use Ghostty/Kitty as long as Kitty is installed and fail as soon as you remove Kitty app.
            # neofetch --backend kitty --source "$HOME/.config/neofetch/image/makeine.webp" \
            #          --size 400px --crop_mode fit
            ;;
        *)
            clear
            neofetch
            ;;
    esac
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$PATH:/home/jelius-sama/.nvm/versions/node/v22.14.0/bin

nvimclean() {
  nvim --clean "$@"
}

suvim() {
  sudo "$(which nvim)" "$@"
}

# # override ssh to support: `ssh kazuma` -> ssh -i ~/.ssh/Kazu.pem ec2-user@<KAZUMA_EC2_IP>
# ssh() {
#   if [[ $# -ge 1 && "$1" == "kazuma" ]]; then
#     shift   # drop the "kazuma" token, leave any extra args (e.g. -p) in $@
#
#     # read the KAZUMA_EC2_IP value from the env file (handles quotes and optional spaces)
#     local ip
#     ip=$(sudo cat /var/kazuma/ec2.env 2>/dev/null | sed -nE "s/^KAZUMA_EC2_IP[[:space:]]*=[[:space:]]*//; s/^['\"]//; s/['\"]$//p" | head -n1)
#
#     if [[ -z "$ip" ]]; then
#       echo "ssh: could not read KAZUMA_EC2_IP from /var/kazuma/ec2.env" >&2
#       return 1
#     fi
#
#     # call the real ssh binary (pass through any remaining args)
#     command ssh -i ~/.ssh/Kazu.pem ec2-user@"$ip" "$@"
#   else
#     # Not the special case — call system ssh normally
#     command ssh "$@"
#   fi
# }

# override ssh to support: `ssh kazuma` -> ssh -i ~/.ssh/Kazu.pem kazuma@<KAZUMA_EC2_IP>
ssh() {
  if [[ $# -ge 1 && "$1" == "kazuma" ]]; then
    shift   # drop the "kazuma" token, leave any extra args (e.g. -p) in $@

    # read the KAZUMA_EC2_IP value from the env file (handles quotes and optional spaces)
    local ip
    ip=$(sudo cat /var/kazuma/ec2.env 2>/dev/null | sed -nE "s/^KAZUMA_EC2_IP[[:space:]]*=[[:space:]]*//; s/^['\"]//; s/['\"]$//p" | head -n1)

    if [[ -z "$ip" ]]; then
      echo "ssh: could not read KAZUMA_EC2_IP from /var/kazuma/ec2.env" >&2
      return 1
    fi

    # call the real ssh binary (pass through any remaining args)
    command ssh -i ~/.ssh/Kazu.pem kazuma@"$ip" "$@"
  else
    # Not the special case — call system ssh normally
    command ssh "$@"
  fi
}

# Silent sudo wrapper
sudo-sh() {
  # Create a temp file for capturing Howdy output
  local tmp=$(mktemp)

  # Run sudo, capturing stderr into tmp and stdout as normal
  command sudo "$@" 2> >(tee "$tmp" >/dev/null)

  # Exit code of sudo command
  local ec=$?

  # Filter and print only relevant lines
  if [[ -s "$tmp" ]]; then
    grep -E "password for|Identified face as" "$tmp"
  fi

  rm -f "$tmp"
  return $ec
}

# autoload -Uz add-zsh-hook
#
# load_neofetch() {
#   anime # Customized neofetch
#   add-zsh-hook -d precmd load_neofetch  # remove hook after first run
# }
#
# add-zsh-hook precmd load_neofetch

alias bat="batcat"
