# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 2
    gaps_out = 2
    # border_size = 2

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15

    # active_opacity = 0.90
    # inactive_opacity = 0.85

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# Define a smooth curve (standard 'myBezier' often used in configs)
bezier = ABSOLUTE_CURVE, 0.05, 0.9, 0.1, 1.05

# Enable the workspace animation: NAME, ONOFF, SPEED, CURVE, STYLE
animation = workspaces, 1, 6, ABSOLUTE_CURVE, slide

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
